### ISSUE TITLE
Tuck arms script crashes in dturtle/unstable  (ros ticket #4955)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_common_actions#17]
Using common 1.3.1, pr2_common_actions 0.3.2

{{{
[ERROR] [WallTime: 1294688920.745819] [35.715000] Exception in your execute callback: 'TuckArmsResult' object has no attribute 'left'
Traceback (most recent call last):
  File "/opt/ros/unstable/stacks/common/actionlib/src/actionlib/simple_action_server.py", line 326, in executeLoop
    self.execute_callback(goal)
  File "/opt/ros/unstable/stacks/pr2_common_actions/pr2_tuck_arms_action/src/pr2_tuck_arms_action/tuck_arms_main.py", line 183, in executeCB
    rospy.logerr("Tuck or untuck arms FAILED: %d %d"%(result.left, result.right))
AttributeError: 'TuckArmsResult' object has no attribute 'left'

}}}

trac data:
- Owner: **mwise**
- Reporter: **watts**
- Reported at: **Mon Jan 10 13:23:42 2011**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/4955

**Comment by ahendrix** [comment]
[watts] This is still a problem in Diamondback. I committed a fix in r50134. Wim, can you release this?

**Comment by ahendrix** [comment]
[wim] Thanks for the patch. The pr2_common_actions stack is now maintained my Melonee.

**Comment by ahendrix** [comment]
[mwise] released in diamondback and unstable as 0.3.4
