### ISSUE TITLE
pr2_tuck_arms_action doesn't abort on failure  (ros ticket #5058)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_common_actions#20]
{{{tuck_arms_main.py:183}}} refers to attributes {{{left}}} and {{{right}}} that don't exist:

{{{
rospy.logerr("Tuck or untuck arms FAILED: %d %d"%(result.left, result.right))
}}}

Traceback:

{{{
Exception in your execute callback: 'TuckArmsResult' object has no attribute 'left'
Traceback (most recent call last):
  File "/opt/ros/diamondback/stacks/common/actionlib/src/actionlib/simple_action_server.py", line 294, in executeLoop
    self.execute_callback(goal)
  File "/opt/ros/diamondback/stacks/pr2_common_actions/pr2_tuck_arms_action/src/pr2_tuck_arms_action/tuck_arms_main.py", line 183, in executeCB
    rospy.logerr("Tuck or untuck arms FAILED: %d %d"%(result.left, result.right))
AttributeError: 'TuckArmsResult' object has no attribute 'left'
}}}

trac data:
- Owner: **mwise**
- Reporter: **tfield**
- Reported at: **Sat Mar  5 14:51:34 2011**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/5058

**Comment by ahendrix** [comment]
[mwise] fix released in diamondback and unstable as 0.3.4
