### ISSUE TITLE
PR2 tuck arms fails in simulation, diamondback  (ros ticket #5079)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_common_actions#21]
This looks like a fairly straightforward problem with tuck arms. I think a message field name changed or something.

{{{

[ERROR] [WallTime: 1300313930.427826] [1.013000] Exception in your execute callback: 'TuckArmsResult' object has no attribute 'left'
Traceback (most recent call last):
  File "/opt/ros/diamondback/stacks/common/actionlib/src/actionlib/simple_action_server.py", line 294, in executeLoop
    self.execute_callback(goal)
  File "/wg/stor5_home4/watts/ros_heaphy/pr2_common_actions/pr2_tuck_arms_action/src/pr2_tuck_arms_action/tuck_arms_main.py", line 183, in executeCB
    rospy.logerr("Tuck or untuck arms FAILED: %d %d"%(result.left, result.right))
AttributeError: 'TuckArmsResult' object has no attribute 'left'
}}}

trac data:
- Owner: **wim**
- Reporter: **watts**
- Reported at: **Wed Mar 16 16:57:34 2011**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/5079

**Comment by ahendrix** [comment]
[tfield] #4955
